ekf_filter_node:
  ros__parameters:
    frequency: 100
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link

    imu0: /camera/imu
    imu0_config: [False, False, False,
                   True,  True,  True,
                   False, False, False,
                   False, False, False,
                   False, False, False]

    odom0: /odom
    odom0_config: [True, True, True,
                    False, False, False,
                    False, False, False,
                    False, False, False,
                    False, False, False]
